name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install backend deps
      working-directory: backend
      run: npm ci
    - name: Lint
      working-directory: backend
      run: npm run lint
    - name: Format check
      working-directory: backend
      run: npm run format:check

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install backend deps
      working-directory: backend
      run: npm ci
    - name: Run tests
      working-directory: backend
      run: npm test --silent
